Some basic patchwork
Abilium-GmbH/FairChain pull request #15
Opened 2021-04-18 15:55 UTC by JethroWarnett

Whilst reading the code, I added some minor improvements
- Replaced some of the booleans with enum
- Cleaned up the style attribute in HTML for toolbar
- Added/Used simple help functions
- Added some assertions

2021-04-18 17:47 UTC, GattoPianista approved these changes
Very nice work!

2021-04-19 14:53 UTC, Korab-Bejta approved these changes

2021-04-19 15:34 UTC, LYCChiang approved these changes

2021-04-20 07:01 UTC, MarcoLord97 requested changes
The clean up looks good, but the Page Layout right side is overwriting the border and exceeding it

2021-04-25 07:20 UTC, MarcoLord97 commented
The changes have been added into to the last pull-request, this one is no more needed

2021-04-25 07:20 UTC, closed without merging