Refactor code
Abilium-GmbH/FairChain pull request #17
Opened 2021-05-02 18:06 UTC by JethroWarnett

Reworked alot of the code to make it cleaner, declarative and smaller. Removed unecessary code. Fixed some bugs in undoRedo and importExportservice. Changed the css of the web app. Removed ngStyle from HTML.

2021-05-02 19:06 UTC, GattoPianista commented on src/app/components/fairChain/fairChain.component.ts
> +  //private nodes: Node[] = [];
Should be deleted

2021-05-02 19:15 UTC, GattoPianista commented on src/app/components/fairChain/fairChain.component.ts
>      this.importExportService.download(filename, text);
Maybe we could just replace a lot of this by making this.importExportService.download(this.nodes, this.edges), then it covertes it to JSON inside and also the file name  can be written inside ExportExportServie

2021-05-02 19:19 UTC, GattoPianista commented on src/app/importExport.service.ts
> +  private data: Data = {
Are we sure we can not use dataset here?

2021-05-02 19:23 UTC, GattoPianista approved these changes
Good work, we should fix some minor things, but you did a lot!

2021-05-03 08:19 UTC, MarcoLord97 approved these changes
As Blendi alredy did a code review and didn't have much to add to his review (gg), I tested out the functionalities.
The versions seems to be buggy, while testing I encountered about 5 bugs:
- while changing node label, editedgemode is activated also, this might be caused by the changed condition in the onClick if statement (I solved it there previously)
- Import/export breaks the change label and color functionalities
- Edit edge label doesn't work anymore
- By editing the color of nodes, also in this case editEdgeMode is activated
Maybe is better to do multiple branch bug fix for each problem before merging in dev

2021-05-03 08:24 UTC, MarcoLord97 requested changes
Wrong approval, first we have to fix the bugs, after we can merge into dev, so please don't merge in the actual situation

2021-05-04 12:16 UTC, Korab-Bejta approved these changes

2021-05-04 12:17 UTC, LYCChiang approved these changes

2021-05-06 12:58 UTC, GattoPianista approved these changes

2021-05-06 13:49 UTC, MarcoLord97 approved these changes
The corrections are good, still missin to fix the changing color/label of nodes is made also on selected edges

2021-05-06 13:51 UTC, merged