Refactor groups
Abilium-GmbH/FairChain pull request #44
Opened 2021-06-01 15:09 UTC by JethroWarnett

Refactored the groups functionality so that its more simple and that it works with undo, redo, imort and export.

2021-06-01 17:01 UTC, LYCChiang requested changes
After you import nodes whose group colors have been changed, if you move a node, the group colors return to the default colors

2021-06-01 17:12 UTC, MarcoLord97 approved these changes
- With undo/redo the snackbar pop up appears everytime
- the icon which appears when hovering a node acts weird if you hover a button then press it to move it

Don't see other problems

2021-06-01 18:47 UTC, GattoPianista approved these changes

2021-06-01 18:47 UTC, LYCChiang approved these changes

2021-06-02 07:32 UTC, Korab-Bejta approved these changes

2021-06-02 08:47 UTC, closed without merging